{% set python_min = '3.10' %}
{% set name = "foyer" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mosdef-hub/foyer/archive/{{ version }}.tar.gz
  sha256: 9f1e21f0c8d0f55f0fd39c90072264bbca2b52ec987a413523b6b54601c113a7

build:
  noarch: python
  number: 1 
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numpy >=2.0,<2.3
    - ele
    - openmm >=7.7,<8.4.0
    - parmed >=3.4.3
    - networkx >=2.5
    - lark
    - requests
    - lxml
    - python >={{ python_min }}
    - gmso >=0.12.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - foyer

about:
  home: https://github.com/mosdef-hub/foyer
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: Atom-typing and force field dissemination.
  description: |
    Foyer is an open-source Python tool that enables users to define and apply
    force field atom-typing rules in a format that is both human- and
    machine-readable and provides a framework for force field dissemination,
    thus eliminating ambiguity in atom-typing and improving reproducibility.
    Foyer defines force fields in an XML format, where SMARTS strings are used
    to define the chemical context of a particular atom type and "overrides"
    are used to set rule precedence, rather than a rigid hierarchical scheme.
  doc_url: https://foyer.mosdef.org/
  dev_url: https://github.com/mosdef-hub/foyer

extra:
  recipe-maintainers:
    - chrisjonesBSU
    - justinGilmer
    - daico007
    - umesh-timalsina
    - CalCraven
